spring:
  application:
    name: manager
  redis:
    host: localhost
    port: 6379
server:
  port: ${PORT:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
